### ISSUE TITLE
How to use the code in a real-world weighted network?

### ISSUE THREAD

**Issue by aliyassin4** [rionbr/distanceclosure#1]
Hello, 

I hope you are doing well, it would be nice if you update the documentation of the distance closure package and put a tutorial of using it in a real world weighted network.

Thank you in advance.

**Comment by rionbr** [comment]
Dear @aliyassin4,
Thank you for the message. Indeed I need to update the documentation since the last major update. I plan to have something up in the next couple of weeks. In the meantime, here's a simple example on how to compute the metric backbone (for relatively small & sparse networks). I hope it helps.

Assuming you have a `G = networkx.Graph()` object where edges have a `distance` attribute,
```python
from distanceclosure.dijkstra import all_pairs_dijkstra_path_length
#
for i, metric_distances in all_pairs_dijkstra_path_length(G, weight='distance', disjunction=sum):
    for j, metric_distance in metric_distances.items():
        if G.has_edge(i, j):
            G[i][j]['metric_distance'] = metric_distance
            G[i][j]['is_metric'] = True if ((metric_distance == G[i][j]['distance']) and (metric_distance != np.inf)) else False
```
Edges in the Backbone are then marked with the flag `is_metric`.

With kind regards,

**Comment by aliyassin4** [comment]
I installed the latest PyPI stable released, and I am getting the following error `ImportError: cannot import name all_pairs_dijkstra_path_length` when trying to import `all_pairs_dijkstra_path_length`.

**Comment by aliyassin4** [comment]
When trying to install the latest development release on GitHub. I also get this error:

```
File "setup.py", line 3, in <module>
    from distanceclosure import __package__, __description__, __version__
  File "/Users/ali/Desktop/distanceclosure/distanceclosure/distanceclosure/__init__.py", line 15, in <module>
    from distanceclosure.dijkstra import *
  File "/Users/ali/Desktop/distanceclosure/distanceclosure/distanceclosure/dijkstra.py", line 120
    raise nx.NodeNotFound(f"Source {source} not in G")
```

**Comment by rionbr** [comment]
Dear Ali,
I apologize you are still having issues. Unfortunately, I could not replicate your errors on my end. The errors look like a python version (2 vs 3) issue, but I'm not sure. Make sure you are running python 3 (I'm running python 3.7.7) and are able to install and work with the necessary requirements (e.g. NetworkX & Cython).

Please try uninstalling any installed versions, by running
```
pip uninstall distanceclosure
```
and then installing directly from the latest github version, by running
```
pip install git+git://github.com/rionbr/distanceclosure
```

I also just pushed a small update to the readme file and some other minor fixes.

Thank you for your patience.
With kind regards,

**Comment by aliyassin4** [comment]
Indeed it was a python version error. Using python 3.7.7 and the requirement packages(networkx, pandas, numpy, scipy and Cython) was able to install the distanceclosure directly from the latest GitHub version. However, trying the example available in the readme file results in this error:
```
NameError                                 Traceback (most recent call last)
/var/folders/y_/k_c4gj5x3rv1kmhprsdpc3lm0000gn/T/ipykernel_54333/3673363907.py in <module>
     21 
     22 # Compute closure (note this will be a fully connected graph. It can be slow for large graphs)
---> 23 C = dc.distance_closure(G, kind='metric', weight='distance')
     24 
     25 # You can now access the new 'metric_distance' value and whether the edge is part of the metric backbone.

~/opt/anaconda3/envs/python3.7.7-env/lib/python3.7/site-packages/distanceclosure/closure.py in distance_closure(D, kind, algorithm, weight, only_backbone, verbose, *args, **kwargs)
     62 
     63     # Dense
---> 64     if w == 'dense':
     65 
     66         raise NotImplementedError('Needs some fine tunning.')

NameError: name 'w' is not defined
```

I also tried this code:

> Dear @aliyassin4, Thank you for the message. Indeed I need to update the documentation since the last major update. I plan to have something up in the next couple of weeks. In the meantime, here's a simple example on how to compute the metric backbone (for relatively small & sparse networks). I hope it helps.
> 
> Assuming you have a `G = networkx.Graph()` object where edges have a `distance` attribute,
> 
> ```python
> from distanceclosure.dijkstra import all_pairs_dijkstra_path_length
> #
> for i, metric_distances in all_pairs_dijkstra_path_length(G, weight='distance', disjunction=sum):
>     for j, metric_distance in metric_distances.items():
>         if G.has_edge(i, j):
>             G[i][j]['metric_distance'] = metric_distance
>             G[i][j]['is_metric'] = True if ((metric_distance == G[i][j]['distance']) and (metric_distance != np.inf)) else False
> ```
> 
> Edges in the Backbone are then marked with the flag `is_metric`.
> 
> With kind regards,

It gives the following error:
```
TypeError                                 Traceback (most recent call last)
/var/folders/y_/k_c4gj5x3rv1kmhprsdpc3lm0000gn/T/ipykernel_53787/1532817936.py in <module>
     20 from distanceclosure.dijkstra import all_pairs_dijkstra_path_length
     21 
---> 22 for i, metric_distances in nx.all_pairs_dijkstra_path_length(G, weight='distance', disjunction=sum):
     23     for j, metric_distance in metric_distances.items():
     24         if G.has_edge(i, j):

TypeError: all_pairs_dijkstra_path_length() got an unexpected keyword argument 'disjunction'
```

Thank you fro your patience and help,
Best regards.

**Comment by rionbr** [comment]
You are right, the last push introduced a bug. It's already corrected. Please uninstall and install again like last time. The sample from the `Readme.md` file should work now.

Thank you! With kind regards,

**Comment by aliyassin4** [comment]
Everything works now, thank you so much!
