### ISSUE TITLE
Install instructions and dependencies

### ISSUE THREAD

**Issue by jcrozum** [rionbr/distanceclosure#11]
The github install instructions are wrong; it should be 
```shell
pip install git+https://github.com/CASCI-lab/distanceclosure
```

Also, the dependencies are not correctly set up. This package requires:
```
scipy
numpy
pandas
networkx
```

**Comment by fcphysics** [comment]
I have updated the installation instructions, but need to investigate the dependencies further.

Specifically you are suggesting to remove cython from the dependencies, which I believe it was used in a previous version but no longer necessary. However, need to double check just to make sure.

**Comment by jcrozum** [comment]
If `Cython` is required for the end-user, we have almost certainly done something wrong. I recall that `CANA` had this issue earlier this year, which we resolved.

**Comment by fcphysics** [comment]
This has been solved in PR 14
