### ISSUE TITLE
Distance and Weighted Graph

### ISSUE THREAD

**Issue by aliyassin4** [rionbr/distanceclosure#3]
Sorry for keeping you busy; If I have a weighted graph where the weights don't represent distances, should I convert the weights to distances before calculating the distance closure in the example in the readme file?

Thank you in advance.

**Comment by rionbr** [comment]
Hey Ali, no problem. 👍 

The short answer is yes, you need to convert edge weights into a *distance* measure (between zero and infinity).

If you have a *proximity* value (between 0 and 1), you can convert between them using the functions [`utils.prox2dist`](https://github.com/rionbr/distanceclosure/blob/master/distanceclosure/utils.py#L25) and [`utils.dist2prox`](https://github.com/rionbr/distanceclosure/blob/master/distanceclosure/utils.py#L48). Note that in machine learning a *dissimilarity* is often used, where in most cases `proximity = 1 - dissimilarity`.

In our research, we usually have a raw count for each pairwise interaction. For instance, how many time two individuals were seen together. Then, we often (globally) normalize this value using a (weighted) Jaccard measure (see [`distanceclosure.distance.py`](https://github.com/rionbr/distanceclosure/blob/master/distanceclosure/distance.py)). That gives us a proximity measure, which we then convert into a distance using the functions above.

If you need more details, check our recent publication: https://academic.oup.com/comnet/article/9/6/cnab021/6403661

Let me know if you have any other questions.
Cheers,

**Comment by aliyassin4** [comment]
Thank you for the explanation. I normalized the weights using the Jaccard measure, as you said. But when I was trying to convert the proximity matrix to a distance matrix I got this error:
```
ValueError                                Traceback (most recent call last)
/var/folders/y_/k_c4gj5x3rv1kmhprsdpc3lm0000gn/T/ipykernel_10663/249814463.py in <module>
     11 # Calculate Proximity and convert to Distance
     12 P = pairwise_proximity(X, metric='jaccard')
---> 13 D = prox2dist(P)

~/opt/anaconda3/envs/python3.7.7-env/lib/python3.7/site-packages/distanceclosure/utils.py in prox2dist(p)
     40         :attr:`dist2prox`
     41     """
---> 42     if (p == 0):
     43         return np.inf
     44     else:

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by rionbr** [comment]
The function `prox2dist` takes a single integer value, I think you are passing an array/matrix. If you pass an array/matrix you need to apply the function to every item.

This might do the trick:
```python
D = np.vectorize(prox2dist)(P)
```

Or simple loop over every value in P and apply the function.

**Comment by aliyassin4** [comment]
Thank you so much!
