### ISSUE TITLE
Dataset Request

### ISSUE THREAD

**Issue by aliyassin4** [rionbr/distanceclosure#4]
Dear @rionbr, 

I am doing a comparative analysis between different graph filtering techniques. Is it possible to send me the datasets you used in this paper [The distance backbone of complex networks](10.1093/comnet/cnab021 )?

I appreciate any help you can provide,
Ali

**Comment by rionbr** [comment]
Hi again Ali,

Several of the networks we used can be freely downloaded from Prof. [Newman's website](http://www-personal.umich.edu/~mejn/netdata/). We only have one or two that comes from our previous work. But if you are comparing different graph filtering techniques, I strongly suggest you source graphs from these repositories.
Another very good repository is Prof. Clauset's [ICON repository](https://icon.colorado.edu/). 

If you can't find a particular network, let me know.

**Comment by aliyassin4** [comment]
Hi Rion,

I couldn't find the biological brain networks and the protein interaction network. Can you send me these networks?

Thanks in advance.

**Comment by rionbr** [comment]
Dear Ali,
The papers on these 2 networks are currently in development or under review. Once they are published the data will be made available.
Kind regards,
